version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend_app
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    container_name: frontend_app
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
